version: "3"
services:
  web:
    image: bahramkb/imageservice:latest
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 500M
      restart_policy:
        condition: on-failure
    environment:
      - IMAGE_ROOT_PATH=/image/
    ports:
      - "9000:9000"
    volumes:
      - /image:/image
    networks:
      - webnet

networks:
  webnet:
