build:
  version: 2016-03-14 # version of the build schema.
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile.builder
      artifacts:
        - /go/src/imageService/ImageService
    production:
      name: bahramkb/imageservice
      dockerfile: Dockerfile.production
      depends_on:
        - builder